### PR TITLE
chore: upgrade to Angular 10

### PR DESCRIPTION
**Pull request by julian-vp**
Hi Bram, 
I upgraded the project to Angular 9, if you want to merge it into the main one.

Thanks!
Julian

### CODE REVIEW

**Comment by beeman** [comment]
Hey @julian-vp, thanks a lot for your contribution. Now that Angular 10 is out, it might make sense to update to that version directly. Would you mind updating this PR to the latest version?

**Comment by julian-vp** [comment]
Hi @beeman. Yes, no worries, I will make an update in the next days.

**Comment by beeman** [comment]
Thanks a lot! 🙏

**Comment by julian-vp** [comment]
Hi @beeman , please have a look at the new updates.
Hope everything is ok.

**Comment by beeman** [comment]
@julian-vp thanks a lot for this, awesome work 🙏!

**Comment by julian-vp** [comment]
No worries @beeman.

**Pull request merged**
